# start name:common
version: '3'

vars:
  BIN_DIR: bin

env:
  BIN_PATH:
    sh: "echo `pwd`/{{ .BIN_DIR }}:$PATH"
  GOBIN:
    sh: "echo `pwd`/{{ .BIN_DIR }}"

tasks:
  default:
    cmds:
      - task: run

  lint:
    desc: Run linter
    cmds:
      - go fmt ./...
      - go vet ./...

  tools:
    desc: Install tool bins
    run: once
    cmds:
      # start name:tools_cmds type:merge
      - go install github.com/gojuno/minimock/v3/cmd/minimock@v3.4.7
      - go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.6.0
    # start name:sources
    sources: # run if changed
      - Taskfile.yml
    generates: # run if missing
      # start name:tools_generates type:merge
      - "{{ .BIN_DIR }}/minimock"
      - "{{ .BIN_DIR }}/oapi-codegen"
      # end

  # start name:generate
  generate:
    deps:
      - tools
    cmds:
      - PATH=$BIN_PATH go generate ./...
      # start name:generate_cmds type:merge
      - PATH=$BIN_PATH oapi-codegen --config=api/oapi-codegen.yml api/swagger.yml
      # start name:post_generate_cmds

  test:
    desc: Run tests
    cmds:
      - go test ./...

  run:
    desc: Run project
    cmds:
      - go run ./cmd/server
